algolia/algoliasearch-client-scala

- README.md
- build.sbt
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/DispatchHttpClient.scala
- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/main/scala/algolia/definitions/WaitForTaskDefinition.scala
- src/main/scala/algolia/inputs/BatchOperations.scala
- src/main/scala/algolia/responses/TaskStatus.scala
- src/main/scala/algolia/responses/Tasks.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
- src/test/scala/algolia/dsl/WaitForTaskTest.scala
- src/test/scala/algolia/integration/IndicesIntegrationTest.scala
- src/test/scala/algolia/integration/IntegrationTest.scala
> Wait for task

- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/main/scala/algolia/inputs/PartialUpdateObject.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
- src/test/scala/algolia/integration/IndicesIntegrationTest.scala
- src/test/scala/algolia/integration/PartialUpdateIntegrationTest.scala
> Add partial update object

- README.md
- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/main/scala/algolia/inputs/BatchOperations.scala
- src/test/scala/algolia/dsl/BatchTest.scala
- src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
- src/test/scala/algolia/integration/PartialUpdateIntegrationTest.scala
> Partial update objects

- README.md
- src/main/scala/algolia/definitions/GetObjectDefinition.scala
- src/main/scala/algolia/inputs/Requests.scala
- src/main/scala/algolia/responses/Results.scala
- src/test/scala/algolia/dsl/GetObjectTest.scala
- src/test/scala/algolia/integration/GetObjectIntegrationTest.scala
> Multiple get objets

- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/main/scala/algolia/definitions/IndexingDefinition.scala
- src/test/scala/algolia/dsl/BatchTest.scala
> Fix: batches of batches

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/DispatchHttpClient.scala
- src/main/scala/algolia/definitions/IndexSettingsDefinition.scala
- src/main/scala/algolia/responses/IndexSettings.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/integration/IndexSettingsIntegrationTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
> Configure an index

- README.md
> Doc: Configure index

- README.md
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/ApiKeyDefinition.scala
- src/main/scala/algolia/definitions/DeleteDefinition.scala
- src/main/scala/algolia/definitions/GetObjectDefinition.scala
- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/main/scala/algolia/responses/ApiKey.scala
- src/main/scala/algolia/responses/CreateUpdateKey.scala
- src/test/scala/algolia/dsl/ApiKeysTest.scala
- src/test/scala/algolia/integration/ApiKeyIntegrationTest.scala
> Add configure/add/etc. api keys

- README.md
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/LogsDefinition.scala
- src/main/scala/algolia/responses/Logs.scala
- src/test/scala/algolia/dsl/LogsTest.scala
- src/test/scala/algolia/integration/LogIntegrationTest.scala
> Fetch logs

- .travis.yml
- README.md
- src/main/scala/algolia/AlgoliaClient.scala
- src/main/scala/algolia/objects/Query.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
> Generate secured api keys

- README.md
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/MultiQueriesDefinition.scala
- src/main/scala/algolia/inputs/MultiQueriesRequests.scala
- src/main/scala/algolia/objects/MultiQueries.scala
- src/main/scala/algolia/responses/SearchResult.scala
- src/test/scala/algolia/dsl/MultiQueriesTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
> Multi-queries

- README.md
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/BrowseIndexDefinition.scala
- src/main/scala/algolia/responses/BrowseResult.scala
- src/test/scala/algolia/dsl/BrowseIndexTest.scala
> Add browsing without query

- README.md
- src/main/scala/algolia/definitions/BrowseIndexDefinition.scala
- src/main/scala/algolia/objects/Query.scala
- src/main/scala/algolia/responses/BrowseResult.scala
- src/test/scala/algolia/dsl/BrowseIndexTest.scala
- src/test/scala/algolia/integration/BrowseIntegrationTest.scala
> Browse by query

- src/main/scala/algolia/AlgoliaClient.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
> Fix hosts automatic fallback

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/ClearDefinition.scala
- src/main/scala/algolia/definitions/DeleteDefinition.scala
- src/main/scala/algolia/definitions/GetDefinition.scala
- src/main/scala/algolia/definitions/IndexSettingsDefinition.scala
- src/main/scala/algolia/definitions/SearchDefinition.scala
- src/main/scala/algolia/definitions/SynonymsDefinition.scala
- src/main/scala/algolia/objects/IndexSettings.scala
- src/main/scala/algolia/objects/QuerySynonyms.scala
- src/main/scala/algolia/objects/Synonym.scala
- src/main/scala/algolia/responses/SearchResult.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/dsl/SynonymsTest.scala
- src/test/scala/algolia/integration/ApiKeyIntegrationTest.scala
- src/test/scala/algolia/integration/BrowseIntegrationTest.scala
- src/test/scala/algolia/integration/GetObjectIntegrationTest.scala
- src/test/scala/algolia/integration/IndexSettingsIntegrationTest.scala
- src/test/scala/algolia/integration/IndicesIntegrationTest.scala
- src/test/scala/algolia/integration/LogIntegrationTest.scala
- src/test/scala/algolia/integration/PartialUpdateIntegrationTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
- src/test/scala/algolia/integration/SynonymIntegrationTest.scala
> Synonyms v2

- src/main/scala/algolia/AlgoliaSyncHelper.scala
- src/main/scala/algolia/definitions/BrowseIndexDefinition.scala
- src/main/scala/algolia/responses/BrowseResult.scala
- src/main/scala/algolia/responses/SearchResult.scala
- src/test/scala/algolia/integration/AlgoliaSyncHelperTest.scala
> Add browse sync and delete by query

- src/main/scala/algolia/definitions/IndexSettingsDefinition.scala
- src/main/scala/algolia/objects/AroundRadius.scala
- src/main/scala/algolia/objects/Query.scala
- src/main/scala/algolia/objects/RemoveStopWords.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/dsl/SearchTest.scala
> Support for new query parameters & forwardToSlaves in changeSettings

- src/main/scala/algolia/responses/Indices.scala
> Indices -> numberOfPendingTask is removed

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/IndexSettingsDefinition.scala
- src/main/scala/algolia/definitions/SynonymsDefinition.scala
- src/main/scala/algolia/objects/IndexSettings.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/dsl/SynonymsTest.scala
> Rename *slaves to *replicas

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/objects/IndexSettings.scala
- src/main/scala/algolia/objects/SearchableAttributes.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/integration/IndexSettingsIntegrationTest.scala
> Rename of attributesToIndex to searchableAttributes

- src/main/scala/algolia/objects/ApiKey.scala
- src/main/scala/algolia/objects/Query.scala
> Secure ApiKeys: Add support for restrictSources

- src/main/scala/algolia/definitions/WaitForTaskDefinition.scala
> waitFor task now waits Infinity

- src/main/scala/algolia/definitions/SearchDefinition.scala
- src/main/scala/algolia/objects/Query.scala
- src/main/scala/algolia/responses/SearchFacetResult.scala
- src/test/scala/algolia/dsl/SearchTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
> feat(search): Add search in facet

- src/main/scala/algolia/objects/Query.scala
- src/test/scala/algolia/dsl/SearchTest.scala
> fix(query): getRankingInfo is a boolean

- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/test/scala/algolia/dsl/BatchTest.scala
- src/test/scala/algolia/integration/PartialUpdateIntegrationTest.scala
> fix(batch): Add partial update on a batch

- src/main/scala/algolia/AlgoliaClient.scala
- src/main/scala/algolia/AlgoliaHttpClient.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/NetworkTest.scala
- src/test/scala/algolia/integration/AlgoliaClientIntegrationTest.scala
> fix(retry): 4XX on retry

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/objects/Ranking.scala
> feat(ranking): Add ranking filters

- .travis.yml
- build.sbt
- project/plugins.sbt
- src/test/scala/algolia/AlgoliaClientTest.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/NetworkTest.scala
- src/test/scala/algolia/integration/AlgoliaClientIntegrationTest.scala
- src/test/scala/algolia/integration/AlgoliaSyncHelperTest.scala
- src/test/scala/algolia/integration/ApiKeyIntegrationTest.scala
- src/test/scala/algolia/integration/BrowseIntegrationTest.scala
- src/test/scala/algolia/integration/GetObjectIntegrationTest.scala
- src/test/scala/algolia/integration/IndexSettingsIntegrationTest.scala
- src/test/scala/algolia/integration/IndicesIntegrationTest.scala
- src/test/scala/algolia/integration/LogIntegrationTest.scala
- src/test/scala/algolia/integration/PartialUpdateIntegrationTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
- src/test/scala/algolia/integration/SynonymIntegrationTest.scala
> feat(scala): Add cross compilation to scala 2.11 and 2.12

- src/main/scala/algolia/AlgoliaClient.scala
- src/main/scala/algolia/AlgoliaHttpClient.scala
- src/test/scala/algolia/AlgoliaTest.scala
> feat(client): Add a .close() method

- build.sbt
> fix(run): Remove coverage from final JARs

- src/main/scala/algolia/responses/SearchResult.scala
> fix(mapping): Fix mapping for SearchResult & fix incorrect usage of formats

- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/test/scala/algolia/NetworkTest.scala
- src/test/scala/algolia/dsl/BasicObject.scala
- src/test/scala/algolia/dsl/BatchTest.scala
- src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
- src/test/scala/algolia/integration/PartialUpdateIntegrationTest.scala
> feat(indexing): Add partial update objects

- src/main/scala/algolia/definitions/MultiQueriesDefinition.scala
- src/test/scala/algolia/dsl/MultipleQueriesTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
> fic(queries): Rename `multiQueries` => `multipleQueries`

- src/main/scala/algolia/definitions/CopyIndexDefinition.scala
- src/main/scala/algolia/definitions/MoveIndexDefinition.scala
- src/main/scala/algolia/inputs/IndexOperation.scala
- src/test/scala/algolia/dsl/CopyIndexTest.scala
- src/test/scala/algolia/dsl/MoveIndexTest.scala
> fix(index): Rename scopes to scope in Copy/Move Index

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/DeleteDefinition.scala
- src/main/scala/algolia/definitions/GetDefinition.scala
- src/main/scala/algolia/definitions/KeyDefinition.scala
- src/main/scala/algolia/definitions/ListDsl.scala
- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/test/scala/algolia/dsl/ApiKeysTest.scala
- src/test/scala/algolia/integration/ApiKeyIntegrationTest.scala
> fix(keys): Rename get.allKeys() in list keys

- src/main/scala/algolia/definitions/IndexSettingsDefinition.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/integration/IndexSettingsIntegrationTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
> fix(settings): Rename changeSettings in setSettings

- src/main/scala/algolia/responses/Indices.scala
- src/main/scala/algolia/responses/Logs.scala
- src/main/scala/algolia/responses/SearchFacetResult.scala
- src/main/scala/algolia/responses/SearchResult.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
Closes #444, #445, #446, #447, #454, #459
> fix(client): Add missing outputs

- src/main/scala/algolia/dsl/SynonymsDsl.scala
- src/main/scala/algolia/dsl/TaskStatusDsl.scala
- src/main/scala/algolia/dsl/WaitForTaskDsl.scala
- src/main/scala/algolia/responses/Tasks.scala
> fix(synonym): Fix synonym Task of synonyms

- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/main/scala/algolia/definitions/BrowseIndexDefinition.scala
- src/main/scala/algolia/definitions/CopyIndexDefinition.scala
- src/main/scala/algolia/definitions/DeleteDefinition.scala
- src/main/scala/algolia/definitions/GetDefinition.scala
- src/main/scala/algolia/definitions/IndexSettingsDefinition.scala
- src/main/scala/algolia/definitions/IndexingBatchDefinition.scala
- src/main/scala/algolia/definitions/KeyDefinition.scala
- src/main/scala/algolia/definitions/ListIndexesDefinition.scala
- src/main/scala/algolia/definitions/LogsDefinition.scala
- src/main/scala/algolia/definitions/MoveIndexDefinition.scala
- src/main/scala/algolia/definitions/MultiQueriesDefinition.scala
- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/main/scala/algolia/definitions/RulesDefinition.scala
- src/main/scala/algolia/definitions/SearchDefinition.scala
- src/main/scala/algolia/definitions/SynonymsDefinition.scala
- src/main/scala/algolia/definitions/TaskStatusDefinition.scala
- src/main/scala/algolia/definitions/WaitForTaskDefinition.scala
- src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
> feat(partial_update): Add createIfNotExists to partialUpdateObject

- src/main/scala/algolia/definitions/GetDefinition.scala
- src/test/scala/algolia/dsl/GetObjectTest.scala
> feat(object): Add attributesToRetrieve for get object

- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/test/scala/algolia/NetworkTest.scala
- src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
> feat(partial): Add partial update objects

- release.sh
In an effort to standardize the release processes of all our API
clients, this commit changes the `release.sh` script in different ways.
First, it will produce ChangeLog entries according the common format
generated by `rake alg:changelog` instead of relying on different
ChangeLog generators (previously `github_changelog_generator` in this
repository).
Then, instead of producing the three following commits at each release:
- `Bump version X.Y.Z`
- `Changelog for vX.Y.Z` [git tag for X.Y.Z is here]
- `Bump snapshot XX.YY.ZZ`
It now produces the two commits instead:
- `chore: Release version X.Y.Z [skip ci]` [git tag for X.Y.Z is here]
- `chore: Bump snapshot to XX.YY.ZZ [skip ci]`
Making the version change of `build.sbt` and the ChangeLog update appear
in the same commit.
The way the …
> chore: Update release script

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE
> Update common files

- src/main/scala/algolia/objects/IndexSettings.scala
- src/main/scala/algolia/objects/Query.scala
- src/test/scala/algolia/dsl/IndexSettingsTest.scala
- src/test/scala/algolia/dsl/SearchTest.scala
Basically closing all those Trello cards:
> Expose new parameters

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/objects/AutomaticFacetFilters.scala
- src/main/scala/algolia/objects/Edit.scala
- src/main/scala/algolia/objects/Rule.scala
- src/main/scala/algolia/objects/TimeRange.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/dsl/RulesTest.scala
- src/test/scala/algolia/integration/RulesIntegrationTest.scala
| New feature?      | yes 
| Related Issue     | no
Added the Enabled feature for Query rules v2
Added the Demote (Hide) test case
Added the TimeFrame test case
Added the Query Edits test case and custom Deserializer
Added Match the Empty Query test case
Added Disjunctive Facet Filters test case and custom Deserializer
> Query Rules v2

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/MCMDefinition.scala
- src/main/scala/algolia/dsl/AssignDsl.scala
- src/main/scala/algolia/dsl/GetDsl.scala
- src/main/scala/algolia/dsl/ListDsl.scala
- src/main/scala/algolia/dsl/PartialUpdateObjectDsl.scala
- src/main/scala/algolia/dsl/RemoveDsl.scala
- src/main/scala/algolia/dsl/SearchDsl.scala
- src/main/scala/algolia/inputs/UserIDAssignment.scala
- src/main/scala/algolia/objects/AutomaticFacetFilters.scala
- src/main/scala/algolia/objects/Edit.scala
- src/main/scala/algolia/objects/RequestOptions.scala
- src/main/scala/algolia/responses/Created.scala
- src/main/scala/algolia/responses/Deleted.scala
- src/main/scala/algolia/responses/MCM.scala
- src/main/scala/algolia/responses/SearchResult.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/integration/MCMIntegrationTest.scala
- src/test/scala/algolia/integration/RulesIntegrationTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
Tests are failing on networking tests and AB Testing tests, those are known/old flaky tests that I'll address in a later PR. MCM is tested and working (same test suite as Java and Go).
> added: Implement methods for Multi Cluster Manangement (MCM)

- build.sbt
| Bug fix?          | yes/no  
| Related Issue     | Fix #509 
Update async-http-client dependency
> Update: async-http-client

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/KeyDefinition.scala
- src/main/scala/algolia/dsl/RestoreDsl.scala
- src/test/scala/algolia/integration/ApiKeyIntegrationTest.scala
| Related Issue     | 
| Need Doc update   | No
Implement `restore key XXX` feature.
> added: implement 'restore key'

- src/main/scala/algolia/definitions/MCMDefinition.scala
- src/main/scala/algolia/dsl/AssignDsl.scala
- src/main/scala/algolia/inputs/UserIDsAssignment.scala
- src/test/scala/algolia/integration/MCMIntegrationTest.scala
> feat(mcm): implement `assign userIDs` to assign multiple userIDs at once

- src/main/scala/algolia/AlgoliaClient.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
> feat(key): implement getSecuredApiKeyRemainingValidity method

- src/main/scala/algolia/objects/IndexSettings.scala
| Related Issue     | Fix #561 
adds `customNormalization` in `IndexSettings`
> feat(index_settings): customNormalization

- src/main/scala/algolia/objects/Query.scala
- src/main/scala/algolia/responses/Alternative.scala
- src/main/scala/algolia/responses/Explain.scala
- src/main/scala/algolia/responses/QueryMatch.scala
- src/main/scala/algolia/responses/SearchResult.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
| Related Issue     | Fix #564 
adds: `explain` parameter and response field.
> feat: adds explain feature

- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/MCMDefinition.scala
- src/main/scala/algolia/dsl/HasDsl.scala
- src/test/scala/algolia/integration/MCMIntegrationTest.scala
| Related Issue     | Fix #566 
Adds the new MCM method `hasPendingMappings` and its related test.
> feat(MCM): hasPendingMappings

- .travis.yml
- build.sbt
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/BatchDefinition.scala
- src/main/scala/algolia/definitions/DeleteDefinition.scala
- src/main/scala/algolia/definitions/IndexingBatchDefinition.scala
- src/main/scala/algolia/definitions/IndexingDefinition.scala
- src/main/scala/algolia/definitions/MultiQueriesDefinition.scala
- src/main/scala/algolia/dsl/BatchDsl.scala
- src/main/scala/algolia/dsl/MultiQueriesDefinitionDsl.scala
- src/main/scala/algolia/http/HttpPayload.scala
- src/main/scala/algolia/inputs/BatchOperations.scala
- src/main/scala/algolia/inputs/MultiQueriesRequests.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/NetworkTest.scala
- src/test/scala/algolia/dsl/SearchTest.scala
- src/test/scala/algolia/integration/ABTestIntegrationTest.scala
- src/test/scala/algolia/integration/AlgoliaSyncHelperTest.scala
- src/test/scala/algolia/integration/ApiKeyIntegrationTest.scala
- src/test/scala/algolia/integration/IndicesIntegrationTest.scala
- src/test/scala/algolia/integration/LogIntegrationTest.scala
- src/test/scala/algolia/integration/MCMIntegrationTest.scala
- src/test/scala/algolia/integration/RecommendationIntegrationTest.scala
- src/test/scala/algolia/integration/SearchIntegrationTest.scala
This PR includes all the changes from @dragisak on #553 plus some dependency updates.
> Testing Scala 2.13

- README.md
| New feature?      | no 
| Related Issue     | -
Add Scala 2.13 support in README
> Add Scala 2.13 support in README

- src/main/scala/algolia/objects/Query.scala
| Related Issue     | Fix #582 
| Need Doc update   | yes/no
adds the `naturalLanguages` parameter.
> feat(query): add naturalLanguages

- src/main/scala/algolia/objects/IndexSettings.scala
> feat(search): expose the enablePersonalization query parameter in settings as well

- src/main/scala/algolia/definitions/PartialUpdateObjectOperationDefinition.scala
- src/main/scala/algolia/dsl/PartialUpdateObjectDsl.scala
- src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
> feat: expose 'increment from' and 'increment set' as new partial update operations

- src/test/scala/algolia/integration/DeleteByIntegrationTest.scala
Delete by tag CTS test:
* Save objects with a tag
* Delete those objects by the same tag
> feat(cts): add delete by tag test

- DOCKERFILER_README.md
- Dockerfile
- README.md
| Related Issue     | Fix #611 
Add repository docker setup
> chore(docker): Add a Dockerfile and a guide to setup Docker

- src/main/scala/algolia/AlgoliaClient.scala
- src/main/scala/algolia/AlgoliaDsl.scala
- src/main/scala/algolia/definitions/DictionaryDefinition.scala
- src/main/scala/algolia/definitions/SaveDictionaryDefinition.scala
- src/main/scala/algolia/definitions/TaskStatusDefinition.scala
- src/main/scala/algolia/definitions/WaitForTaskDefinition.scala
- src/main/scala/algolia/dsl/ClearDsl.scala
- src/main/scala/algolia/dsl/DeleteDsl.scala
- src/main/scala/algolia/dsl/DictionaryDsl.scala
- src/main/scala/algolia/dsl/GetDsl.scala
- src/main/scala/algolia/dsl/ReplaceDsl.scala
- src/main/scala/algolia/dsl/SearchDsl.scala
- src/main/scala/algolia/dsl/SetDsl.scala
- src/main/scala/algolia/dsl/WaitForTaskDsl.scala
- src/main/scala/algolia/objects/Dictionary.scala
- src/main/scala/algolia/objects/DictionarySettings.scala
- src/main/scala/algolia/objects/QueryDictionary.scala
- src/main/scala/algolia/responses/SearchDictionaryResult.scala
- src/main/scala/algolia/responses/Tasks.scala
- src/test/scala/algolia/AlgoliaClientTest.scala
- src/test/scala/algolia/AlgoliaTest.scala
- src/test/scala/algolia/dsl/DictionaryTest.scala
- src/test/scala/algolia/integration/DictionaryIntegrationTest.scala
> feat(dictionaries): dictionaries API implementation

- src/main/scala/algolia/objects/IndexSettings.scala
- src/main/scala/algolia/objects/Query.scala
| New feature?      | yes    
| BC breaks?        | yes*   
| Related Issue     | Fix #615, Fix #616
\* _due to [case class](https://docs.scala-lang.org/overviews/scala-book/case-classes.html) use, unavoidable without refactoring_
> feat(settings): add attributesToTransliterate and decompoundQuery params

- src/main/scala/algolia/responses/Indices.scala
> feat(index): add primary param to Index

- src/main/scala/algolia/responses/BrowseResult.scala
- src/main/scala/algolia/responses/SearchFacetResult.scala
- src/main/scala/algolia/responses/SearchResult.scala
> fix(search): optional fields in results responses

- src/main/scala/algolia/objects/Query.scala
- src/test/scala/algolia/dsl/SearchTest.scala
> feat: add `enableReRanking` query parameter
