algolia/algoliasearch-client-scala

build.sbt, src/main/scala/algolia/DispatchHttpClient.scala, src/main/scala/algolia/definitions/ListIndexesDefinition.scala, src/test/scala/algolia/AlgoliaClientTest.scala
Change the default httpReadTimeout from 30s to 2s.
Closes #96
=> Fixing timeout on DNS, and SNI support

src/main/scala/algolia/AlgoliaClient.scala, src/test/scala/algolia/AlgoliaClientTest.scala, src/test/scala/algolia/integration/IndicesIntegrationTest.scala
Without specifying the `charset`, the search client was failing to index UTF-8 strings (such as "Bézier").
I would love to see this fix in a 1.7.1 release. Thanks!
=> Specify UTF-8 character set in Content-Type request header

src/main/scala/algolia/objects/Query.scala, src/test/scala/algolia/dsl/SearchTest.scala
=> Add custom query parameters

src/main/scala/algolia/AlgoliaClient.scala, src/test/scala/algolia/AlgoliaClientTest.scala
=> Add custom HEADERS to the requests

src/main/scala/algolia/AlgoliaClient.scala, src/test/scala/algolia/AlgoliaClientTest.scala
=> Migrate user agent to new format

build.sbt
=> feat(json4s): Be less restrictiv for json4s dependency version, to make it compatible with Spark

build.sbt
This PR makes minor changes to the sbt build to take advantage of some helpers from sbt and to use the `isSnapshot` setting key (which boils down to `version.endsWith("-SNAPSHOT")` in the end).
=> Minor build clean up: use isSnapshot and sbt helpers

build.sbt
This was causing an incompatibility for us - would love to not have to shade the algolia library or independently manage a fork to deal with it. Any reason we couldn't increase to the latest json4s version?
=> bump json4s version from 3.4.0 to 3.5.2

src/main/scala/algolia/AlgoliaDsl.scala, src/main/scala/algolia/definitions/TaskStatusDefinition.scala, src/main/scala/algolia/definitions/WaitForTaskDefinition.scala, src/test/scala/algolia/AlgoliaTest.scala, src/test/scala/algolia/dsl/TaskStatusTest.scala, src/test/scala/algolia/integration/TaskStatusIntegrationTest.scala
This PR makes two changes:
- Adds a `TaskStatusDefinition` to simply query the status of task without waiting for it
- In the `WaitForTaskDefinition`, replaces the creation of `Timer` with a `HashedWheelTimer`
The motivation of the first change is to allow the caller to handle the retries (if any) instead of imposing a strategy. It also allows **not** to create a new `Timer` (and therefore a new `Thread`) for each call.
The motivation of the second change is to allow multiple `waitFors` without creating new timer `Threads` for each one. 
At [Flow](https://github.com/flowcommerce), we ran into issues while checking the status of multiple index tasks with aggressive `baseDelay` as it ended up creating several thousands of `Threads`. The recursive implementation of the …
=> Add tasks status definition + use HashedWheelTimer in waitFor

src/main/scala/algolia/dsl/RulesDsl.scala, src/test/scala/algolia/integration/RulesIntegrationTest.scala
Follow up of https://github.com/algolia/algoliasearch-client-go/issues/397.
=> fix: Prevent saving a rule with an empty objectID

src/main/scala/algolia/objects/IndexSettings.scala, src/test/scala/algolia/dsl/IndexSettingsTest.scala
| New feature?      | yes   
| Related Issue     | 
Implement the `keepDiacriticsOnCharacters` setting.
⚠️ The tests not passing are network related and have nothing to do with the PR ⚠️ 
⚠️ I let you update the CHANGELOG, I am not to sure about the new format ⚠️
Because it's currently blocking to merge https://github.com/algolia/doc/pull/1727
=> Feat(keepDiacriticsOnCharacter)

src/main/scala/algolia/definitions/BatchDefinition.scala, src/main/scala/algolia/definitions/DeleteDefinition.scala, src/main/scala/algolia/definitions/SafeDeleteObjectDefinition.scala, src/main/scala/algolia/dsl/DeleteDsl.scala, src/main/scala/algolia/inputs/SafeDeleteObjectOperation.scala, src/test/scala/algolia/dsl/BatchTest.scala, src/test/scala/algolia/dsl/DeleteObjectTest.scala, src/test/scala/algolia/inputs/SafeDeleteObjectOperationTest.scala
As we recently discovered, the following request was able to delete an entire index:
```
delete from "index" `object` ""
```
To fix this issue, we deprecated this way of deleting the object with the following approach:
```
val op: Option[SafeDeleteObjectOperation] = SafeDeleteObjectOperation("index", "objectID")
delete objectFromIndex op.get
```
which forces the user to pass non-empty index name and objectID, otherwise the returned `Option` is `None`. This is made possible by the use of private constructors on the `SafeDeleteObjectDefinition` and of a companion object with a public `apply()` method that only lets the user instantiate a `SafeDeleteObjectDefinition` with valid i.e. non-empty parameters.
=> Fixed: Introduce 'delete objectFromIndex X' to deprecate 'delete object X from index Y'

src/main/scala/algolia/AlgoliaClient.scala, src/main/scala/algolia/AlgoliaDsl.scala, src/main/scala/algolia/definitions/InsightsEventDefinition.scala, src/main/scala/algolia/definitions/StrategyDefinition.scala, src/main/scala/algolia/dsl/GetDsl.scala, src/main/scala/algolia/dsl/SendDsl.scala, src/main/scala/algolia/dsl/SetDsl.scala, src/main/scala/algolia/http/HttpPayload.scala, src/main/scala/algolia/inputs/InsightsEvent.scala, src/main/scala/algolia/objects/Query.scala, src/main/scala/algolia/objects/Strategy.scala, src/main/scala/algolia/responses/Insights.scala, src/main/scala/algolia/responses/Personalization.scala, src/test/scala/algolia/dsl/SendTest.scala, src/test/scala/algolia/dsl/StrategyTest.scala
```scala
client.execute {
send event ClickedFilters("eventName", "indexName", []string{"filter"})
send event ClickedObjectIDs("eventName", "indexName", []string{"objectID"})
send event ClickedObjectIDsAfterSearch("eventName", "indexName", []string{"objectID"}, []string{42} /* positions */, "queryID")
// Conversion events
send event ConvertedObjectIDs("eventName", "indexName", []string{"objectID"})
send event ConvertedObjectIDsAfterSearch("eventName", "indexName", []string{"objectID"}, "queryID")
send event ConvertedFilters("eventName", "indexName", []string{"filter"})
// View events
send event ViewedFilters("eventName", "indexName", []string{"filter"})
send event ViewedObjectIDs("eventName", "indexName", []string{"objectID"})
// Send raw events
send event InsightsEvent(...)
send events …
```
=> Insights & Perso

src/main/scala/algolia/dsl/DeleteDsl.scala
| Related Issue     | n/a
The new 'delete objectFromIndex X' syntax introduced in #498 was missing a typeclass to execute the new SafeDeleteObjectDefinition. 
The following code currently does not compile with `could not find implicit value for parameter executable: algolia.Executable[algolia.definitions.SafeDeleteObjectDefinition,RESULT]`:
```
val op: Option[SafeDeleteObjectOperation] = SafeDeleteObjectOperation("index", "objectID")
algoliaClient.execute(delete objectFromIndex op.get)
```
=> Add missing Executable typeclass for SafeDeleteObjectDefinition

src/main/scala/algolia/AlgoliaHttpClient.scala
| Related Issue     | Fix #500
Make sure that `DnsNameResolver.close()` is called when the `AlgoliaClient.close()` is called.
Problem is better described in #500 but essentially, prior to that fix, sockets were leaked and could lead to exhaustion when many `AlgoliaClient` got instantiated in the same JVM.
@Ant-hem @ElPicador If you guys could help me know how to run a single ScalaTest with specific JVM options, I'd be happy to know because I couldn't find an easy way of doing so to integrate the test suggested by @tanin47 in his issue. Thanks in advance for any help.
=> fixed: Ensure that the DnsNameResolver is closed when the AlgoliaClient is

src/main/scala/algolia/inputs/ABTest.scala, src/main/scala/algolia/responses/ABTest.scala, src/test/scala/algolia/integration/ABTestIntegrationTest.scala, src/test/scala/algolia/integration/SearchIntegrationTest.scala
| Related Issue     | 
Implement the new `customSearchParameters` field in ABTest variants to let users deploy AA tests.
=> added: support new customSearchParameters field in ABTest variants for AA testing

.travis.yml, src/main/scala/algolia/definitions/BatchDefinition.scala, src/test/scala/algolia/dsl/PartialUpdateObjectTest.scala
| Related Issue     | Fix #544 
`createIfNotExists false` was ignored when generating batch of `partialUpdate` operations. This was reported by @jtanguy in https://github.com/algolia/algoliasearch-client-scala/pull/544 at first but the some tests were missing to handle all use-cases and the proposed solution was not fixing the issue.
By avoiding to ignore the `createIfNotExists` field of `PartialUpdateOneObjectDefinition` in `BatchDefinition.transform`, we can now generate the proper payload according to the boolean value.
=> Fix partial objects no create in batch

src/main/scala/algolia/objects/IndexSettings.scala
| Related Issue     | Fix #541 
Implement the new `indexLanguages` setting which is an array of strings.
Currently, only `["ja"]` is supported by the engine.
=> adds: indexLanguages settings properties

src/main/scala/algolia/AlgoliaDsl.scala, src/main/scala/algolia/objects/Alternatives.scala, src/test/scala/algolia/integration/RulesIntegrationTest.scala
| Related Issue     | Fix #542  
This PR adds the`Alternatives` parameter in QueryRules conditions
Alternatives may transform into JSON object in the future.
=> feat(queryRules/alternatives)

src/main/scala/algolia/responses/SearchResult.scala
=> fix(search): correctly type automaticRadius field of search response

src/main/scala/algolia/responses/Logs.scala
=> feat(search): expose innerQueries response field when performing a `getLogs`

src/main/scala/algolia/objects/Rule.scala, src/test/scala/algolia/AlgoliaTest.scala, src/test/scala/algolia/dsl/RulesTest.scala, src/test/scala/algolia/integration/RulesIntegrationTest.scala
Close #591 
This is a breaking change since the `Rule.condition` field type has to be
changed from `Condition` to `Option[Condition]`. IMHO it's fine to break the
compatibility here since the condition type was incorrect in the first place,
and it's more important to stay align as much as we can with other API clients.
=> feat(rule): implement multi-condition rules

.circleci/config.yml
This commit fixes the environment variable shell expansion in the
release step of the CircleCI configuration. It also makes sure the
variables are not expanded when displaying the error message.
=> chore(ci): fix release step environment variables checks

build.sbt, src/main/scala/algolia/http/HttpPayload.scala
| Related Issue     | 
Remove dependency on `"io.lemonlabs" %% "scala-uri"`.
Libraries like `algolia-clieant-scala` are intended for use in many different applications built by Algolia's clients. 
It's in the interest of library maintainer to make extra effort to minimize 3rd party dependencies. All in order to prevent
possible transitive library version conflicts for their users.
For example, since we needed some functionality that comes with `scala-uri` 2.x, we had to go into
a hassle to "shade" `algolia-client-scala` and it's dependencies to avoid version conflict with
`scala-uri` 1.x.
`scala-uri` is only minimally used …
=> Remove dependency on scala-uri

src/main/scala/algolia/AlgoliaDsl.scala, src/test/scala/algolia/dsl/IndexSettingsTest.scala
Due to some CI limitations, this is a fork of #603.
| New feature?      |no    
| Need Doc update   | /no
For the deserialization, added dots a a valid part of an attribute, since this is how you denote nested attributes.
Nested attributes caused the deserialization to fail. I.e. one customer ranking nested attribute caused a failure of the deserialization of the full list of customer rankings.
Modified "IndexSettings serialization/deserialization" unit test with this scenario.
=> fix(deserialization): added dot as a valid in an attribute name for the deserialization

src/main/scala/algolia/objects/Rule.scala
| New feature?      | yes    
| BC breaks?        | yes*     
| Related Issue     | Fix #617  
\* _due to [case class](https://docs.scala-lang.org/overviews/scala-book/case-classes.html) use, unavoidable without refactoring_
=> feat(rules): add filters param to rules condition

src/main/scala/algolia/objects/IndexSettings.scala, src/main/scala/algolia/objects/RenderingContent.scala, src/main/scala/algolia/objects/Rule.scala, src/main/scala/algolia/responses/SearchResult.scala
The new Facet Ordering feature providing the order of facet widgets and facet values.
=> feat: facets ordering

src/main/scala/algolia/objects/IndexSettings.scala, src/main/scala/algolia/objects/Query.scala, src/main/scala/algolia/responses/SearchResult.scala
Virtual indices feature (aka virtual replicas) provides a few new parameters:
Search & Settings parameters:
* **relevancyStrictness** 
- integer value [0-100]  
- relevancy score to apply to search in virtual index. Bigger value means less, but more relevant results, lesser value - more less relevant results
Search response:
* **appliedRelevancyStrictness** 
- integer value [0-100]
- relevancy score to apply to the search in virtual index. 
* **nbSortedHits** 
- integer value
- number of relevant hits to display in case of non-zero `relevancyStrictness` applied
=> feat(virtual indices): Virtual indices related parameters

src/main/scala/algolia/responses/ABTest.scala
add `trackedSearchCount` field to `VariantResponse`
=> feat(analytics): add trackedSearchCount to variant response

src/main/scala/algolia/AlgoliaDsl.scala, src/main/scala/algolia/definitions/SynonymsDefinition.scala, src/test/scala/algolia/dsl/SynonymsTest.scala
| BC breaks?        | yes (TBC)   
| Related Issue     | Fix #609
Rename `saveSynonyms`'s  `replaceExistingSynonyms` to `clearExistingSynonyms` for consistency.
=> refact(search): `replaceExistingSynonyms` to `clearExistingSynonyms`

src/main/scala/algolia/AlgoliaDsl.scala, src/test/scala/algolia/dsl/BatchTest.scala, src/test/scala/algolia/dsl/DeleteObjectTest.scala
| Bug fix?          | ~yes
| Related Issue     | n/a
Move `DeleteObjectOperation` serialization:
from`{"action":"deleteObject","objectID":"toto"}`
to `{"action":"deleteObject","body":{"objectID":"toto"}}`
=> refact: batch delete operation serialization

src/main/scala/algolia/AlgoliaHttpClient.scala
| Related Issue     | Fix #650 
Shutdown internal thread when closing `AlgoliaHttpClient`.
Fixing issue #650
=> shutdown DNS event loop when closing HTTP client

src/main/scala/algolia/objects/Query.scala, src/test/scala/algolia/dsl/SearchTest.scala
| Related Issue     | Fix #...  
| Need Doc update   | maybe
Add similarQuery to params sent to Algolia.
While similarQuery is exposed by the Query class type, it isn't used when it comes time to build the params string. The result is that similarQuery isn't sent to Algolia during execution.
=> similarQuery not accounted for in param string

build.sbt
=> fix: update `netty-codec` to version `4.1.86.Final`
